# Generated by Django 4.2.13 on 2024-06-25 14:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
                ('image', models.ImageField(help_text='this hold the contestant image', null=True, upload_to='images/', verbose_name='Contestant Images')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
                ('contestant_id', models.CharField(blank=True, help_text='this hold the contestant id which will be automatically generated', max_length=10, null=True, verbose_name='Contestant ID')),
                ('first_name', models.CharField(help_text='this hold the First Name of the contestant', max_length=10, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='this hold the middle name of the contestant', max_length=10, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text='this hold the last name of the contestant ', max_length=10, null=True, verbose_name='Last Name')),
                ('stage_name', models.CharField(help_text='this hold the stage name of the contestant ', max_length=10, null=True, verbose_name='Stage Name')),
                ('contestant_inspiration', models.CharField(help_text='this hold the contestant inspiration toward the competition', max_length=50, null=True, verbose_name='Contestant Inspiration')),
                ('contestant_images', models.ManyToManyField(to='users.contestantimage')),
            ],
            options={
                'verbose_name': 'Contestant Profile',
                'verbose_name_plural': 'Contestant Profile',
                'ordering': ['-created_date'],
            },
        ),
    ]
