# Generated by Django 4.2.13 on 2024-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contestantimage_contestant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='first_name',
            field=models.CharField(help_text='this hold the First Name of the contestant', max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='last_name',
            field=models.CharField(help_text='this hold the last name of the contestant ', max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='middle_name',
            field=models.CharField(blank=True, help_text='this hold the middle name of the contestant', max_length=100, null=True, verbose_name='Middle Name'),
        ),
    ]
