# Generated by Django 4.2.13 on 2024-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contestant_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='contestant_id',
            field=models.CharField(blank=True, help_text='this hold the contestant id which will be automatically generated', max_length=100, null=True, verbose_name='Contestant ID'),
        ),
    ]
