# Generated by Django 4.2.13 on 2024-06-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_contestant_contestant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='contestant_id',
            field=models.CharField(blank=True, help_text='this hold the contestant id which will be automatically generated', max_length=10, null=True, verbose_name='Contestant ID'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='stage_name',
            field=models.CharField(help_text='this hold the stage name of the contestant ', max_length=100, null=True, verbose_name='Stage Name'),
        ),
    ]
