# Generated by Django 4.2.13 on 2024-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_contestant_contestant_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestantimage',
            options={'ordering': ['-created_date'], 'verbose_name': 'Contestant Image', 'verbose_name_plural': 'Contestant Image'},
        ),
        migrations.AddField(
            model_name='contestant',
            name='number_of_vote',
            field=models.IntegerField(blank=True, help_text='this displays the contestant vote count', null=True, verbose_name='Contestant Inspiration'),
        ),
    ]
