# Generated by Django 4.2.13 on 2024-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_contestantimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='number_of_vote',
            field=models.IntegerField(blank=True, default=0, help_text='this displays the contestant vote count', null=True, verbose_name='Contestant Inspiration'),
        ),
    ]
