# Generated by Django 4.2.13 on 2024-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_contestant_number_of_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of Contestant'),
        ),
    ]
