# Generated by Django 4.2.13 on 2024-06-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-created_date'], 'verbose_name': 'Transactions', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transactions',
            name='voter_phone_number',
            field=models.BigIntegerField(blank=True, help_text='this displays the voter phone number', null=True, verbose_name='Voter phone Number'),
        ),
    ]
