# Generated by Django 4.2.13 on 2024-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_contestantvideo_contestant_contestant_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='contestant_videos',
        ),
        migrations.AddField(
            model_name='contestant',
            name='contestant_videos',
            field=models.JSONField(default=list),
        ),
    ]
