# Generated by Django 4.2.13 on 2024-07-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_contestant_contestant_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='middle_name',
        ),
    ]
