# Generated by Django 4.2.13 on 2024-07-15 10:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_contestant_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
                ('stage', models.CharField(blank=True, help_text='this hold the Stage which will is active', max_length=10, null=True, verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Contestant Stage',
                'verbose_name_plural': 'Contestant Stage',
                'ordering': ['-created_date'],
            },
        ),
    ]
