# Generated by Django 4.2.13 on 2024-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_contestantstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantstage',
            name='stage',
            field=models.CharField(blank=True, help_text='this hold the Stage which will is active', max_length=100, null=True, verbose_name='Stage'),
        ),
    ]
